1server:
  port: 9713

spring:
  application:
    name: discovery-server

eureka:
  instance:
    lease-expiration-duration-in-seconds: 60
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
    #  defaultZone: http://10.20.2.12:9713/eureka/
      defaultZone: http://${server-ip}:9713/eureka/

logging:
  file:
    name: ./logs/${spring.application.name}.log

  level:
    com:
      netflix:
        eureka :
        discovery: OFF

