server:
  port: 9713

spring:
  application:
    name: discovery-server

eureka:
  server:
    enable-self-preservation: false
    expected-client-renewal-interval-seconds: 60
    eviction-interval-timer-in-ms: 45
    renewal-threshold-update-interval-ms: 5
  instance:
    lease-expiration-duration-in-seconds: 60
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9713/eureka/

logging:
#  file:
#    path: /logs
#    name: ${spring.application.name}.log

  level:
    com:
      netflix:
        eureka :
        discovery: OFF

